;;; Basic repositories.
(require 'package)
(setq package-enable-at-startup nil)
(setq package-archives '(("elpa"  . "http://tromey.com/elpa/")
			 ("gnu"   . "http://elpa.gnu.org/packages/")
			 ("melpa" . "https://melpa.org/packages/")
			 ("org"   . "https://orgmode.org/elpa/")))
(package-initialize)

;;; Secure the `use-package` macro.
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

;; My dotfiles are symlinked in place so this makes the startup way less
;; annoying.
(setq vc-follow-symlinks t)

;;; Modeline.
(use-package doom-modeline
  :ensure t
  :init (doom-modeline-mode 1))

;;; Aesthetic easy stuff.
(tool-bar-mode -1)
(menu-bar-mode -1)
(scroll-bar-mode -1)
(fringe-mode '(10 . 1))

;;; Sane buffer killing.
(defun murder-current-buffer ()
  "directly kill the current buffer"
  (interactive)
  (kill-buffer (current-buffer)))

(global-set-key (kbd "C-x k") #'murder-current-buffer)

;;; Sane window splitting.
(defun split-and-follow-horizontally ()
  "split current window horizontally and move the cursor in it"
  (interactive)
  (split-window-below)
  (balance-windows)
  (other-window 1))

(defun split-and-follow-vertically ()
  "split current window vertically and move the cursor in it"
  (interactive)
  (split-window-right)
  (balance-windows)
  (other-window 1))

(global-set-key (kbd "C-x 2") 'split-and-follow-horizontally)
(global-set-key (kbd "C-x 3") 'split-and-follow-vertically)

;;; Biggest QOL change.
(defalias 'yes-or-no-p 'y-or-n-p)

;;; Parenthesis.
(show-paren-mode 1)

(setq electric-pair-pairs '(
			    (?\{ . ?\})
			    (?\( . ?\))
			    (?\[ . ?\])
			    (?\" . ?\")
			    ))
(electric-pair-mode t)

;;; IDO + SMEX for nice completion in minibuffer.
(setq ido-enable-flex-matching t)
(setq ido-everywhere t)
(ido-mode 1)

(use-package ido-completing-read+
  :ensure t
  :config
  (ido-ubiquitous-mode 1))

(use-package smex
  :ensure t
  :config
  (global-set-key (kbd "M-x") 'smex))

;;; Magit.
(use-package magit
  :ensure t
  :config
  (global-set-key (kbd "C-c g") #'magit-status))

;;; Which-key.
(use-package which-key
  :ensure t
  :init
  (which-key-mode))

;;; Backups in a better place
(setq backup-directory-alist '(("." . "~/emacs-backups"))
      backup-by-copying      t
      delete-old-versions    t
      kept-new-versions      10
      kept-old-versions      3)

;; Load stuff.
(load "~/.emacs.d/dired-stuff.el")

;;; ==========================
;;; Autogenerated stuff below.
;;; ==========================

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-enabled-themes '(modus-operandi))
 '(package-selected-packages
   '(which-key magit smex ido-completing-read+ use-package doom-modeline)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#ffffff" :foreground "#000000" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "ADBO" :family "Source Code Pro")))))
