# kakrc!

# A nice colorscheme.
colorscheme gruvbox-dark

# Width of a tab and indent with 4 spaces.
set-option global tabstop 4
set-option global indentwidth 4

# Always keep one line and three columns displayed around the cursor.
set-option global scrolloff 1,3

# Display the status bar on top.
set-option -add global ui_options terminal_status_on_top=true

# No more clippy.
set-option -add global ui_options terminal_assistant=none

# Display line numbers.
add-highlighter global/ number-lines -hlcursor -relative

# Highlight matching braces.
add-highlighter global/ show-matching

# Buffer navigation.
map -docstring "close buffer" global user q ": db<ret>"
map -docstring "next buffer" global user <space> ": bn<ret>"

# Make bindings.
map -docstring "make" global user m ":make<ret>"
map -docstring "make run" global user r ":make run<ret>"

# System's clipboard bindings.
map -docstring "yank to clipboard" global user y  "<a-|> xclip -selection clipboard<ret>"
map -docstring "paste from clipboard" global user p "<a-!> xclip -selection clipboard -o<ret>"

# HTML
hook global BufSetOption filetype=html %{
    map -docstring "insert paragraph below" buffer user s "o<lt>p<gt><ret><lt>/p<gt><a-;>O<backspace><backspace><backspace><backspace>"
}
